name: "Clair Test"
description: "Image Vulnerability Test"

inputs:
  updater:
    description: 'Set Updater E.G. debian'
    required: true
  report_path:
    description: 'Path to Report'
    required: true
  report_format:
    description: 'Report format. Values: xml | json | text'
    required: false
    default: 'xml'
  image:
    description: 'Container image to scan'
    required: true

runs:
  using: "composite"
  steps:
    - run: sudo setfacl --modify user:65534:rw /var/run/docker.sock
      shell: bash
    - run: docker-compose up -d
      shell: bash
    - run: docker tag vulnerables/web-dvwa localhost:5000/${{ inputs.image }}
      shell: bash
    - run: docker push localhost:5000/${{ inputs.image }}
      shell: bash
    - run: while true; do echo "Checking Clair Status" && sleep 5 && docker logs clair 2>&1 | grep "ready" && break; done && sleep 30
      shell: bash
    - run: |
        export REGISTRY_INSECURE=TRUE
        export IP_REG=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' registry)
        docker exec clair /clairctl-linux-amd64 -D report -o ${{ inputs.report_format }} $IP_REG:5000/${{ inputs.image }} > ${{ inputs.report_path }}
      shell: bash
