name: "Clair Test"
description: "Image Vulnerability Test"

inputs:
  updater:
    description: 'Set Updater E.G. debian'
    required: true
  report_path:
    description: 'Path to Report'
    required: true

runs:
  using: "composite"
  steps:
    - run: sed -i 's/SET_UPDATER/${{ inputs.updater }}/g' config.yaml
      shell: bash
    - run: docker-compose up -d
      shell: bash  
    - run: while true; do echo "Checking Clair Status" && sleep 5 && docker logs clair 2>&1 | grep "ready" && break; done 
      shell: bash
    - run: docker exec clair clairctl -D report -o xml vulnerables/web-dvwa > ${{ inputs.report_path }}
      shell: bash
    
