name: "Clair Test"
description: "Image Vulnerability Test"

inputs:
  updater:
    description: 'Set Updater E.G. debian'
    required: true
  report_path:
    description: 'Path to Report'
    required: true
  report_format:
    description: 'Report format. Values: xml | json | text'
    required: false
    default: 'xml'
  image:
    description: 'Container image to scan'
    required: true

runs:
  using: "composite"
  steps:
    - run: sed -i 's/SET_UPDATER/${{ inputs.updater }}/g' config.yaml
      shell: bash
    - run: docker-compose up -d
      shell: bash
    - run: while true; do echo "Checking Clair Status..." && sleep 5 && docker logs clair 2>&1 | grep "ready" && break; done 
      shell: bash
    - run: docker-compose ps
      shell: bash
#    - run: docker pull vulnerables/web-dvwa && docker tag vulnerables/web-dvwa:latest web-dvwa:test-action && docker image ls && docker manifest create web-dvwa:test-action --platform linux/amd64 && sleep 5
    - run: |
        docker build -t ivan:test -f - . << EOF
        FROM vulnerables/web-dvwa:latest
        EOF
      shell: bash
    - run: docker-compose up -d && docker exec clair /clairctl-linux-amd64 analyze library/postgres
      shell: bash
    - run: docker-compose up -d && docker exec clair /clairctl-linux-amd64 report library/postgres
      shell: bash
    #- run: docker-compose up -d && docker exec clair clairctl -D report -o ${{ inputs.report_format }} ghcr.io/the-iron-bank-of-braavos/clair/ivan:test > ${{ inputs.report_path }}
    #  shell: bash
      
#    - run: sudo setfacl --modify user:65534:rw /var/run/docker.sock
#      shell: bash
#    - run: docker-compose up -d
#      shell: bash
#    - run: docker tag vulnerables/web-dvwa localhost:5000/${{ inputs.image }}
#      shell: bash
#    - run: docker push localhost:5000/${{ inputs.image }}
#      shell: bash
#    - run: while true; do echo "Checking Clair Status" && sleep 5 && docker logs clair 2>&1 | grep "ready" && break; done 
#      shell: bash
#    - run: |
#        export IP_REG=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' registry) && docker-compose up -d
#        docker exec clair clairctl -D report -o ${{ inputs.report_format }} $IP_REG:5000/${{ inputs.image }} > ${{ inputs.report_path }}
#      shell: bash
