name: "Clair Test"
description: "Image Vulnerability Test"

inputs:
  updater:
    description: 'Set Updater E.G. debian'
    required: true
  report_path:
    description: 'Path to Report'
    required: true
  report_format:
    description: 'Report format. Values: xml | json | text'
    required: false
    default: 'json'
  image:
    description: 'Container image to scan'
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        sed -i 's/SET_UPDATER/${{ inputs.updater }}/g' $GITHUB_ACTION_PATH/config.yaml
        docker-compose -f $GITHUB_ACTION_PATH/docker-compose.yml -f $GITHUB_ACTION_PATH/docker-compose-clair.yml up -d
        while true; do echo "Checking Clair Status" && sleep 5 && curl http://localhost:6060 &> /dev/null 2>&1 && break; done
        docker pull ${{ inputs.image }}
        docker tag ${{ inputs.image }} localhost:5000/${{ inputs.image }} && docker push localhost:5000/${{ inputs.image }}
        docker exec clair clairctl -D report -o ${{ inputs.report_format }} localhost:5000/${{ inputs.image }} > ${{ inputs.report_path }}
      shell: bash

