version: '3.7'

services:
  registry:
    container_name: registry
    networks:
      clair:
        aliases:
          - registry
    image: registry:2.7
    ports:
      - 5000:5000
      
  postgres:
    container_name: postgres
    image: postgres@sha256:fab2a4a9fa7af0464b665f90818894481b524035ddc337bf09d5321624cee644
#    cpus: '0.40'
#    mem_limit: 2g
    networks:
      clair:
        aliases:
          - postgres
    volumes:
      - postgres-data/:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_PASSWORD=clair
      - POSTGRES_USER=clair
      - POSTGRES_DB=clair
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clair"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432

  clair:
    container_name: clair
#    cpus: '0.60'
#    mem_limit: 4g
    networks:
      clair:
        aliases:
          - clair
    image: quay.io/projectquay/clair:4.2.0
    #image: quay.io/coreos/clair
    environment:
      - CLAIR_MODE=combo
      - CLAIR_CONF=/config/config.yaml
      #- IP_REG=${IP_REG}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - ./config.yaml:/config/config.yaml:ro
      - ./clairctl-linux-amd64:/clairctl-linux-amd64:ro
      - /tmp/:/tmp/
    depends_on:
      - "postgres"
      - "registry"
    links:
      - postgres
      # - registry
    ports:
      - 6060:6060

volumes:
  postgres-data:

networks:
  clair:
    name: clair
