name: prueba-POC

on: [push]
       
jobs:  
  clair-scan:
    name: Scan image with Clair
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Pull image to local registry
      run: |
       docker pull vulnerables/web-dvwa:latest
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: $GITHUB_TOKEN
    - name: Clair Test
      id: clairtest
      uses: ./
      with:
       image: "test"
       report_format: xml
       updater: debian
       report_path: clair-report.xml
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: clair-result
        path: clair-report.xml
