name: prueba-POC

on: [push]
       
jobs:  
  clair-scan:
    name: Scan image with Clair
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Pull image to local registry
      run: |
       docker pull vulnerables/web-dvwa
       docker tag vulnerables/web-dvwa test/test:1.0.0
    - name: Clair Test
      id: clairtest
      uses: ./
      with:
       image: "debian:unstable-slim"
       report_format: xml
       updater: debian
       report_path: clair-report.xml
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: clair-result
        path: clair-report.xml
